### PR TITLE
TLC-151:Enabled the 'Death information' section in the registration form

### PR DESCRIPTION
**Pull request by kazlaw**
Ticket here: https://mekomsolutions.atlassian.net/browse/TLC-151

Initial test below:

[Screencast from 08-07-24 09:26:11.webm](https://github.com/mekomsolutions/bahmni-distro-tlc/assets/36139599/2a60e8a5-73a6-4fb5-853a-dbe1da3286de)

### CODE REVIEW

**Comment by kazlaw** [comment]
[Screencast from 17-07-24 16:15:32.webm](https://github.com/user-attachments/assets/e6da3d1a-9089-440b-a693-758a3f412a2c)

**Review by Ruhanga — COMMENTED** [review]
The build fails @kazlaw. Is there no concept already existing for the failing line?
Screenshot 2024-07-18 at 11 06 50

**Comment by kazlaw** [comment]
> The build fails @kazlaw. Is there no concept already existing for the failing line? Screenshot 2024-07-18 at 11 06 50

I missed it when making this commit here:https://github.com/mekomsolutions/bahmni-distro-tlc/pull/9/commits/a0fc2a85f749aa36327a82c8f974ac6373885448 They already exist at the Haiti level so its simply a UUID swap and deleting of the duplicate

**Comment by kazlaw** [comment]
[Screencast from 18-07-24 12:59:46.webm](https://github.com/user-attachments/assets/7c71a91a-96a2-4232-acd3-acaf0c255875)


This should be good to go.

**Review by Ruhanga — APPROVED** [review]
LGTM

**Comment by kazlaw** [comment]
@Ruhanga please merge I am unable to

**Pull request merged**
